# PANDAS

![link text](https://www.kindpng.com/picc/m/574-5747046_python-pandas-logo-transparent-hd-png-download.png)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Topics to be covered in 4 parts as follows:
1. Creating, reading and writing
2. Indexing, selecting, assigning
3. Grouping and sorting, Data Types and Missing values, Renaming and Combining 
4. summary functions and maps

# **`Part1`**

# Introduction

The first step in most data analytics projects is reading the data file. In this exercise, you'll create Series and DataFrame objects, both by hand and by reading data files.

In [ ]:
#loading libraries
import pandas as pd

## 1. Creating Dataframe

In the cell below, create a DataFrame `fruits` that looks like this:

![](https://i.imgur.com/Ax3pp2A.png)

In [ ]:
# Create a dataframe matching the above diagram and assign it to the variable fruits.
fruits = pd.DataFrame([[30, 21]], columns=['Apples', 'Banana'])
print(fruits)

   Apples  Banana
0      30      21

## 2. Setting index for dataframe

Create a dataframe `fruit_sales` that matches the diagram below:

![](https://i.imgur.com/CHPn7ZF.png)

In [ ]:
# Create a dataframe matching the above diagram and assign it to the variable fruit_sales.
fruit_sales = pd.DataFrame([[35, 21], [41, 34]], columns=['Apples', 'Bananas'],
                index=['2017 Sales', '2018 Sales'])
fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

## 3. Creating Series

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [ ]:
quantities = ['4 cups', '1 cup', '2 large', '1 can']
items = ['Flour', 'Milk', 'Eggs', 'Spam']
ingredients = pd.Series(quantities, index=items)


# Check your answer
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
dtype: object

## 4. Create and display a dataframe

 create and display a DataFrame called `animals`:

In [ ]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

##What is difference between series and dataframe?

Series is a type of list in pandas which can take integer values, string values, double values and more. ... Series can only contain single list with index, whereas dataframe can be made of more than one series or we can say that a dataframe is a collection of series that can be used to analyse the data.

#**`Part2`**

In [ ]:
# importing libraries
import pandas as pd

In [ ]:
#importing dataset
reviews = pd.read_csv("/content/drive/MyDrive/masterclass/winemag-data-130k-v2.csv", index_col=0)

Look at an overview of your data by running the following line.

In [ ]:
# by default .head() shows 5 rows
reviews.head()

    country  ...               winery
0     Italy  ...              Nicosia
1  Portugal  ...  Quinta dos Avidagos
2        US  ...            Rainstorm
3        US  ...           St. Julian
4        US  ...         Sweet Cheeks

[5 rows x 13 columns]

# Exercises

## 1. Selecting single column from Dataframe

Select the `description` column from `reviews` and assign the result to the variable `desc`.

In [ ]:
# Your code here
desc = reviews.description
desc

# or you can do it like this reviews['description']

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
                                ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

In [ ]:
first_description = reviews['description']
first_description

0         Aromas include tropical fruit, broom, brimston...
1         This is ripe and fruity, a wine that is smooth...
2         Tart and snappy, the flavors of lime flesh and...
3         Pineapple rind, lemon pith and orange blossom ...
4         Much like the regular bottling from 2012, this...
                                ...
129966    Notes of honeysuckle and cantaloupe sweeten th...
129967    Citation is given as much as a decade of bottl...
129968    Well-drained gravel soil gives this wine its c...
129969    A dry style of Pinot Gris, this is crisp with ...
129970    Big, rich and off-dry, this is powered by inte...
Name: description, Length: 129971, dtype: object

Follow-up question: what type of object is `desc`? If you're not sure, you can check by calling Python's `type` function: `type(desc)`.

## 2. Selecting a first value from a perticular column

Select the first value from the description column of `reviews`, assigning it to variable `first_description`.

In [ ]:
first_description = reviews.description.iloc[0]

first_description

"Aromas include tropical fruit, broom, brimstone and dried herb. The palate isn't overly expressive, offering unripened apple, citrus and dried sage alongside brisk acidity."

<font color='purple '>Note that while this is the preferred way to obtain the entry in the DataFrame,
many other options will return a valid result, such as reviews.description.loc[0], reviews.description[0], and more!</font>

## 3. Selecting first record

Select the first row of data (the first record) from `reviews`, assigning it to the variable `first_row`.

In [ ]:
first_row = reviews.iloc[0]
first_row

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

## 4. Selecting first 10 values from specific column

Select the first 10 values from the `description` column in `reviews`, assigning the result to variable `first_descriptions`.

Hint: format your output as a pandas Series.

In [ ]:
first_descriptions = reviews.description.iloc[:10]
first_descriptions

0    Aromas include tropical fruit, broom, brimston...
1    This is ripe and fruity, a wine that is smooth...
2    Tart and snappy, the flavors of lime flesh and...
3    Pineapple rind, lemon pith and orange blossom ...
4    Much like the regular bottling from 2012, this...
5    Blackberry and raspberry aromas show a typical...
6    Here's a bright, informal red that opens with ...
7    This dry and restrained wine offers spice in p...
8    Savory dried thyme notes accent sunnier flavor...
9    This has great depth of flavor with its fresh ...
Name: description, dtype: object

<font color='purple'>Note that many other options will return a valid result, such as desc.head(10) and reviews.loc[:9, "description"].</font>

## 5. Selecting records with specific index values

Select the records with index labels `1`, `2`, `3`, `5`, and `8`, assigning the result to the variable `sample_reviews`.

In other words, generate the following DataFrame:

![](https://i.imgur.com/sHZvI1O.png)

In [ ]:
indices = [1, 2, 3, 5, 8]
sample_reviews = reviews.loc[indices]
sample_reviews

    country  ...               winery
1  Portugal  ...  Quinta dos Avidagos
2        US  ...            Rainstorm
3        US  ...           St. Julian
5     Spain  ...               Tandem
8   Germany  ...          Heinz Eifel

[5 rows x 13 columns]

## 6. Selecting records with specific index values and columns

Create a variable `df` containing the `country`, `province`, `region_1`, and `region_2` columns of the records with the index labels `0`, `1`, `10`, and `100`. In other words, generate the following DataFrame:

![](https://i.imgur.com/FUCGiKP.png)

In [ ]:
cols = ['country', 'province', 'region_1', 'region_2']
indices = [0, 1, 10, 100]
df = reviews.loc[indices, cols]
df.head()

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

## what is difference between loc and iloc?


> `iloc` uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. 
`loc`, meanwhile, indexes inclusively. 

> This is particularly confusing when the DataFrame index is a simple numerical list, e.g. `0,...,1000`. In this case `df.iloc[0:1000]` will return 1000 entries, while `df.loc[0:1000]` return 1001 of them! To get 1000 elements using `loc`, you will need to go one lower and ask for `df.iloc[0:999]`.

## 7. Selecting specific columns using iloc and loc

Create a variable `df` containing the `country` and `variety` columns of the first 100 records. 

Hint: you may use `loc` or `iloc`. When working on the answer this question and the several of the ones that follow, keep the following "gotcha" described in the tutorial:

In [ ]:
cols = ['country', 'variety']
df = reviews.loc[:99, cols]
#or

cols_idx = [0, 11]
df = reviews.iloc[:100, cols_idx]
df

     country                   variety
0      Italy               White Blend
1   Portugal            Portuguese Red
2         US                Pinot Gris
3         US                  Riesling
4         US                Pinot Noir
..       ...                       ...
95    France                     Gamay
96    France                     Gamay
97        US                  Riesling
98     Italy                Sangiovese
99        US  Bordeaux-style Red Blend

[100 rows x 2 columns]

## 8. Creating Dataframe with one condition

Create a DataFrame `italian_wines` containing reviews of wines made in `Italy`. Hint: `reviews.country` equals what?

In [ ]:
italian_wines = reviews[reviews.country == 'Italy']
italian_wines

       country  ...                           winery
0        Italy  ...                          Nicosia
6        Italy  ...                  Terre di Giurfo
13       Italy  ...              Masseria Setteporte
22       Italy  ...               Baglio di Pianetto
24       Italy  ...                        Canicattì
...        ...  ...                              ...
129929   Italy  ...             Col Vetoraz Spumanti
129943   Italy  ...  Baglio del Cristo di Campobello
129947   Italy  ...         Feudo Principi di Butera
129961   Italy  ...                              COS
129962   Italy  ...                         Cusumano

[19540 rows x 13 columns]

## 9. Creating Dataframe with more than 1 conditions

Create a DataFrame `top_oceania_wines` containing all reviews with at least 95 points (out of 100) for wines from Australia or New Zealand.

In [ ]:
top_oceania_wines = reviews.loc[
    (reviews.country.isin(['Australia', 'New Zealand']))
    & (reviews.points >= 95)
]
top_oceania_wines

            country  ...                       winery
345       Australia  ...  Chambers Rosewood Vineyards
346       Australia  ...  Chambers Rosewood Vineyards
348       Australia  ...  Chambers Rosewood Vineyards
349       Australia  ...                     Torbreck
356       Australia  ...                  Jasper Hill
360       Australia  ...                     Torbreck
365       Australia  ...                    Wakefield
14354     Australia  ...                      Kaesler
16538     Australia  ...                      Lambert
28573     Australia  ...              Clarendon Hills
34502     Australia  ...                     Standish
34506     Australia  ...                     Standish
38988     Australia  ...                     Penfolds
39059     Australia  ...                    Wakefield
39961     Australia  ...                     Penfolds
39962     Australia  ...                     Penfolds
45809     Australia  ...              Clarendon Hills
56953     Australia  ...                     Penfolds
56956     Australia  ...                     Standish
56957     Australia  ...                 Thorn Clarke
56959     Australia  ...                     Henschke
59977     Australia  ...                 Hickinbotham
59984     Australia  ...                    Heartland
67096     Australia  ...            R.L. Buller & Son
67101     Australia  ...  Chambers Rosewood Vineyards
76392     Australia  ...                  Jasper Hill
77028     Australia  ...                     Penfolds
77036     Australia  ...                     Penfolds
77037     Australia  ...                     Torbreck
77042     Australia  ...             John Duval Wines
77044     Australia  ...                   Kilikanoon
77046     Australia  ...                     Torbreck
83357     Australia  ...                     Penfolds
84815     Australia  ...                     Torbreck
84816     Australia  ...                     Nashwauk
87128     Australia  ...                 Kay Brothers
87137     Australia  ...                    Moss Wood
87143     Australia  ...                    Wakefield
91851   New Zealand  ...                 Trinity Hill
98386     Australia  ...                   D'Arenberg
99318     Australia  ...                     Henschke
99330     Australia  ...                     Penfolds
99340     Australia  ...                     Torbreck
109427    Australia  ...  Chambers Rosewood Vineyards
109434    Australia  ...                   D'Arenberg
122421    Australia  ...                     Glaetzer
122430    Australia  ...                     Glaetzer
122507  New Zealand  ...             Squawking Magpie
122939    Australia  ...                     Torbreck

[49 rows x 13 columns]

#**`Part 3`**

Maps allow us to transform data in a DataFrame or Series one value at a time for an entire column. However, often we want to group our data, and then do something specific to it. As you'll learn, we do this with the groupby() operation.

In these exercises we'll apply groupwise analysis to our dataset.

In [ ]:
reviews.head()
# print(reviews.points.unique())

    country  ...               winery
0     Italy  ...              Nicosia
1  Portugal  ...  Quinta dos Avidagos
2        US  ...            Rainstorm
3        US  ...           St. Julian
4        US  ...         Sweet Cheeks

[5 rows x 13 columns]

The general process of groupby involves the following steps:

*  Split: Splitting the data into groups based on some criteria.
*  Apply: Applying a function to each group independently:
    .sum()
    .count()
    .mean() 
    .std() 
    .aggregate()
    .apply()
    .etc..
* Combine: Combining the results into a data structure.

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DV0101EN/labs/Images/Mod3Fig4SplitApplyCombine.png" height=400 align="center">

In [ ]:
# print(type(reviews.groupby('points')))
print(reviews.groupby('points').points.count())
# reviews.groupby('points').first()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

- `groupby()` created a group of reviews which allotted the same point values to the given wines. Then, for each of these groups, we grabbed the `points()` column and counted how many times it appeared. `value_counts()` is just a shortcut to this `groupby()` operation.

### After doing the groupby using points column find the max value of price in the first group formed i.e 80.

In [ ]:
# get_group to get the specific group
reviews.groupby('points').get_group(100)

          country  ...                       winery
345     Australia  ...  Chambers Rosewood Vineyards
7335        Italy  ...                   Avignonesi
36528      France  ...                         Krug
39286       Italy  ...        Tenuta dell'Ornellaia
42197    Portugal  ...             Casa Ferreirinha
45781       Italy  ...                 Biondi Santi
45798          US  ...                    Cardinale
58352      France  ...      Château Léoville Barton
89728      France  ...               Louis Roederer
89729      France  ...                        Salon
111753     France  ...    Château Lafite Rothschild
111754      Italy  ...             Casanova di Neri
111755     France  ...         Château Cheval Blanc
111756     France  ...   Château Léoville Las Cases
113929         US  ...                Charles Smith
114972   Portugal  ...              Quinta do Noval
118058         US  ...                       Verité
122935     France  ...           Château Haut-Brion
123545         US  ...                       Cayuse

[19 rows x 13 columns]


We can use any of the `summary functions` we've used before with this data. For example, to get the costliest wine in each point value category, we can do the following:

In [ ]:
reviews.groupby('points').price.max()

points
80       69.0
81      130.0
82      150.0
83      225.0
84      225.0
85      320.0
86      170.0
87      800.0
88     3300.0
89      500.0
90      510.0
91     2013.0
92      750.0
93      770.0
94     1125.0
95      973.0
96     2500.0
97     2000.0
98     1900.0
99      850.0
100    1500.0
Name: price, dtype: float64

<font color='green'>So maximum value for the first group formed i.e. for 80 is `69`</font>

**`apply() -`**  So here we will now see how to use the apply method. we can directly access what we wanna access from dataframe using apply() method,and we can then manipulate the data in any way we want to. For example, here's one way of `selecting the name of the first wine reviewed from each winery in the dataset:`

In [ ]:
reviews.groupby('points').apply(lambda df: df.title.iloc[0])

points
80     Viña Tarapacá 2015 Gran Reserva Chardonnay (Le...
81     Pura 8 2010 Grand Reserve Pinot Noir (Rapel Va...
82       Mémoires 2015 Rosé (Coteaux Varois en Provence)
83         Koyle 2015 Costa Pinot Noir (Colchagua Costa)
84     Three Brothers 2014 Zero Degree Dry Riesling (...
85     Casa Silva 2008 Gran Reserva Petit Verdot (Col...
86     Clarksburg Wine Company 2010 Chenin Blanc (Cla...
87                     Nicosia 2013 Vulkà Bianco  (Etna)
88                  Fattoria Sardi 2015 Rosato (Toscana)
89           David Fulton 2008 Petite Sirah (St. Helena)
90     Beaumont 2005 Hope Marguerite Chenin Blanc (Wa...
91     Le Riche 2003 Cabernet Sauvignon Reserve Caber...
92     Dopff & Irion 2004 Schoenenbourg Grand Cru Ven...
93     Claiborne & Churchill 2014 Twin Creeks Estate ...
94         Sandeman 2015 Quinta do Seixo Vintage  (Port)
95     Jasper Hill 2013 Georgia's Paddock Shiraz (Hea...
96                        Oremus 2005 Eszencia  (Tokaji)
97     Robert Weil 2014 Kiedrich Gräfenberg Trockenbe...
98     Chambers Rosewood Vineyards NV Rare Muscadelle...
99     Quilceda Creek 2008 Cabernet Sauvignon (Columb...
100    Chambers Rosewood Vineyards NV Rare Muscat (Ru...
dtype: object

- Python allows you to create anonymous function i.e function having no names using a facility called `lambda function`.

- <font color='green'>Lambda functions are small functions usually not more than a line. It can have any number of arguments just like a normal function. The body of lambda functions is very small and consists of only one expression.</font>

- `To create a lambda function first write keyword lambda followed by one of more arguments separated by comma (,), followed by colon a (:), followed by a single line expression.`

For even more fine-grained control, you can also `group by more than one column`. For an example, here's how `we would pick out the best wine by country and province:`

In [ ]:
reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()]) #star

                              country  ...                winery
country   province                     ...
Argentina Mendoza Province  Argentina  ...  Bodega Catena Zapata
          Other             Argentina  ...                Colomé
Armenia   Armenia             Armenia  ...              Van Ardi
Australia Australia Other   Australia  ...       Marquis Philips
          New South Wales   Australia  ...            De Bortoli
...                               ...  ...                   ...
Uruguay   Juanico             Uruguay  ...        Familia Deicas
          Montevideo          Uruguay  ...                 Bouza
          Progreso            Uruguay  ...                Pisano
          San Jose            Uruguay  ...        Castillo Viejo
          Uruguay             Uruguay  ...               Narbona

[425 rows x 13 columns]

### After doing the groupby using country column find the max value of price for group named Argentina

In [ ]:
reviews.groupby(['country']).get_group('Argentina').price.sum().max()

92060.0

`Another groupby() method worth mentioning is agg(), which lets you run a bunch of different functions on your DataFrame simultaneously.` For example, we can generate a simple statistical summary of the dataset as follows:

In [ ]:
grouped_single = reviews.groupby(['country']).price.agg([min, max,sum])
print((grouped_single))

                         min     max        sum
country
Argentina                4.0   230.0    92060.0
Armenia                 14.0    15.0       29.0
Australia                5.0   850.0    81294.0
Austria                  7.0  1100.0    86105.0
Bosnia and Herzegovina  12.0    13.0       25.0
Brazil                  10.0    60.0     1117.0
Bulgaria                 8.0   100.0     2065.0
Canada                  12.0   120.0     9071.0
Chile                    5.0   400.0    91793.0
China                   18.0    18.0       18.0
Croatia                 12.0    65.0     1807.0
Cyprus                  11.0    21.0      179.0
Czech Republic          15.0    45.0      291.0
Egypt                    NaN     NaN        0.0
England                 25.0    95.0     3566.0
France                   5.0  3300.0   731289.0
Georgia                  9.0    40.0     1623.0
Germany                  5.0   775.0    89586.0
Greece                   8.0    79.0    10310.0
Hungary                 10.0   764.0     5894.0
India                   10.0    20.0      120.0
Israel                   8.0   150.0    15535.0
Italy                    5.0   900.0   670873.0
Lebanon                 13.0    75.0     1074.0
Luxembourg              16.0    30.0      140.0
Macedonia               15.0    20.0      187.0
Mexico                   8.0   108.0     1875.0
Moldova                  8.0    42.0      988.0
Morocco                 14.0    40.0      546.0
New Zealand              7.0   130.0    37112.0
Peru                    10.0    68.0      289.0
Portugal                 5.0  1000.0   127814.0
Romania                  4.0   320.0     1829.0
Serbia                  15.0    42.0      294.0
Slovakia                16.0    16.0       16.0
Slovenia                 7.0    90.0     1985.0
South Africa             5.0   330.0    31897.0
Spain                    4.0   770.0   185459.0
Switzerland             21.0   160.0      597.0
Turkey                  14.0   120.0     2217.0
US                       4.0  2013.0  1984659.0
Ukraine                  6.0    13.0      129.0
Uruguay                 10.0   130.0     2878.0

I’d recommend renaming the new columns and you see that your grouping column is now the dataframe’s index. Reset your index to make this easier to work with later on.

In [ ]:
# rename columns
grouped_single.rename(columns={'min':'price_min'})

# reset index to get grouped columns back
grouped_single = grouped_single.reset_index()
print(grouped_single)

                   country   min     max        sum
0                Argentina   4.0   230.0    92060.0
1                  Armenia  14.0    15.0       29.0
2                Australia   5.0   850.0    81294.0
3                  Austria   7.0  1100.0    86105.0
4   Bosnia and Herzegovina  12.0    13.0       25.0
5                   Brazil  10.0    60.0     1117.0
6                 Bulgaria   8.0   100.0     2065.0
7                   Canada  12.0   120.0     9071.0
8                    Chile   5.0   400.0    91793.0
9                    China  18.0    18.0       18.0
10                 Croatia  12.0    65.0     1807.0
11                  Cyprus  11.0    21.0      179.0
12          Czech Republic  15.0    45.0      291.0
13                   Egypt   NaN     NaN        0.0
14                 England  25.0    95.0     3566.0
15                  France   5.0  3300.0   731289.0
16                 Georgia   9.0    40.0     1623.0
17                 Germany   5.0   775.0    89586.0
18                  Greece   8.0    79.0    10310.0
19                 Hungary  10.0   764.0     5894.0
20                   India  10.0    20.0      120.0
21                  Israel   8.0   150.0    15535.0
22                   Italy   5.0   900.0   670873.0
23                 Lebanon  13.0    75.0     1074.0
24              Luxembourg  16.0    30.0      140.0
25               Macedonia  15.0    20.0      187.0
26                  Mexico   8.0   108.0     1875.0
27                 Moldova   8.0    42.0      988.0
28                 Morocco  14.0    40.0      546.0
29             New Zealand   7.0   130.0    37112.0
30                    Peru  10.0    68.0      289.0
31                Portugal   5.0  1000.0   127814.0
32                 Romania   4.0   320.0     1829.0
33                  Serbia  15.0    42.0      294.0
34                Slovakia  16.0    16.0       16.0
35                Slovenia   7.0    90.0     1985.0
36            South Africa   5.0   330.0    31897.0
37                   Spain   4.0   770.0   185459.0
38             Switzerland  21.0   160.0      597.0
39                  Turkey  14.0   120.0     2217.0
40                      US   4.0  2013.0  1984659.0
41                 Ukraine   6.0    13.0      129.0
42                 Uruguay  10.0   130.0     2878.0

# Grouping by Multiple Columns

`groupby()` is slightly different in the fact that, depending on the operation we run, it will sometimes result in what is called a multi-index.

In [ ]:
countries_reviewed = reviews.groupby(['country']).description.agg([len])
countries_reviewed

                          len
country
Argentina                3800
Armenia                     2
Australia                2329
Austria                  3345
Bosnia and Herzegovina      2
Brazil                     52
Bulgaria                  141
Canada                    257
Chile                    4472
China                       1
Croatia                    73
Cyprus                     11
Czech Republic             12
Egypt                       1
England                    74
France                  22093
Georgia                    86
Germany                  2165
Greece                    466
Hungary                   146
India                       9
Israel                    505
Italy                   19540
Lebanon                    35
Luxembourg                  6
Macedonia                  12
Mexico                     70
Moldova                    59
Morocco                    28
New Zealand              1419
Peru                       16
Portugal                 5691
Romania                   120
Serbia                     12
Slovakia                    1
Slovenia                   87
South Africa             1401
Spain                    6645
Switzerland                 7
Turkey                     90
US                      54504
Ukraine                    14
Uruguay                   109

In [ ]:
z = countries_reviewed.index
type(z)

pandas.core.indexes.multi.MultiIndex

Again by using `reset_index()` method you make these indices column again.

In [ ]:
grouped_s= countries_reviewed.reset_index()
grouped_s.head()

                  country   len
0               Argentina  3800
1                 Armenia     2
2               Australia  2329
3                 Austria  3345
4  Bosnia and Herzegovina     2

#Sorting

Looking again at countries_reviewed we can see that grouping returns data in index order, not in value order. That is to say, when outputting the result of a groupby, the order of the rows is dependent on the values in the index, not in the data.

The sort_values() method is used to get data in the order what we want.

In [ ]:
countries_reviewed = countries_reviewed.reset_index()
countries_reviewed.sort_values(by = 'len')

                   country    len
9                    China      1
34                Slovakia      1
13                   Egypt      1
1                  Armenia      2
4   Bosnia and Herzegovina      2
24              Luxembourg      6
38             Switzerland      7
20                   India      9
11                  Cyprus     11
12          Czech Republic     12
33                  Serbia     12
25               Macedonia     12
41                 Ukraine     14
30                    Peru     16
28                 Morocco     28
23                 Lebanon     35
5                   Brazil     52
27                 Moldova     59
26                  Mexico     70
10                 Croatia     73
14                 England     74
16                 Georgia     86
35                Slovenia     87
39                  Turkey     90
42                 Uruguay    109
32                 Romania    120
6                 Bulgaria    141
19                 Hungary    146
7                   Canada    257
18                  Greece    466
21                  Israel    505
36            South Africa   1401
29             New Zealand   1419
17                 Germany   2165
2                Australia   2329
3                  Austria   3345
0                Argentina   3800
8                    Chile   4472
31                Portugal   5691
37                   Spain   6645
22                   Italy  19540
15                  France  22093
40                      US  54504

- `sort_values()` defaults to an ascending sort, where the lowest values go first. However, most of the time we want a descending sort, where the higher numbers go first. That goes thusly:

In [ ]:
countries_reviewed.sort_values(by='len', ascending=False)

                   country    len
40                      US  54504
15                  France  22093
22                   Italy  19540
37                   Spain   6645
31                Portugal   5691
8                    Chile   4472
0                Argentina   3800
3                  Austria   3345
2                Australia   2329
17                 Germany   2165
29             New Zealand   1419
36            South Africa   1401
21                  Israel    505
18                  Greece    466
7                   Canada    257
19                 Hungary    146
6                 Bulgaria    141
32                 Romania    120
42                 Uruguay    109
39                  Turkey     90
35                Slovenia     87
16                 Georgia     86
14                 England     74
10                 Croatia     73
26                  Mexico     70
27                 Moldova     59
5                   Brazil     52
23                 Lebanon     35
28                 Morocco     28
30                    Peru     16
41                 Ukraine     14
25               Macedonia     12
33                  Serbia     12
12          Czech Republic     12
11                  Cyprus     11
20                   India      9
38             Switzerland      7
24              Luxembourg      6
1                  Armenia      2
4   Bosnia and Herzegovina      2
9                    China      1
34                Slovakia      1
13                   Egypt      1

To sort by index values, use the companion method `sort_index()`. This method has the same arguments and default order:

In [ ]:
countries_reviewed.sort_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

#Dtypes

The data type for a column in a DataFrame or a Series is known as the dtype.

You can use the dtype property to grab the type of a specific column. For instance, we can get the dtype of the price column in the reviews DataFrame:

In [ ]:
reviews.price.dtype

dtype('float64')

Alternatively, the dtypes property returns the dtype of every column in the DataFrame:

In [ ]:
reviews.dtypes

country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

- Data types tell us something about how pandas is storing the data internally. float64 means that it's using a 64-bit floating point number; int64 means a similarly sized integer instead, and so on.

- <font color='brown'>One peculiarity to keep in mind (and on display very clearly here) is that columns consisting entirely of strings do not get their own type; they are instead given the object type.</font>

### So why columns consisting entirely of strings do not get their own type,intead have object type?

![Screenshot from 2020-11-19 19-12-33.png]()

It's possible to convert a column of one type into another wherever such a conversion makes sense by using the **`astype()`** function. For example, we may transform the `points` column from its existing `int64` data type into a `float64` data type:

In [ ]:
reviews.points.astype('float')

0         87.0
1         87.0
2         87.0
3         87.0
4         87.0
          ...
129966    90.0
129967    90.0
129968    90.0
129969    90.0
129970    90.0
Name: points, Length: 129971, dtype: float64

A DataFrame or Series index has its own dtype, too:

In [ ]:
reviews.index.dtype

dtype('int64')

`Pandas also supports more exotic data types, such as categorical data and timeseries data. `

# Missing Data
So the missing values are given NaN values,short for "Not a Number". For technical reasons these NaN values are always of the float64 dtype.


<font color='blue'>Pandas provides some methods specific to missing data. To select NaN entries you can use `pd.isnull()` (or its companion `pd.notnull()`). This is meant to be used thusly:</font>

In [ ]:
#check if there are null values
reviews.isnull().values.any()

True

In [ ]:
# reviews[pd.isnull(reviews.country)]
pd.notnull(reviews.country)
# pd.notnull(reviews.designation)

0         True
1         True
2         True
3         True
4         True
          ...
129966    True
129967    True
129968    True
129969    True
129970    True
Name: country, Length: 129971, dtype: bool

In [ ]:
# checking weather the top five values are null or not for specific column 
reviews.country.notnull().head()

0    True
1    True
2    True
3    True
4    True
Name: country, dtype: bool

In [ ]:
#by this way we can see how many entries per column are empty
reviews.isnull().sum()

country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

<font color='blue'>Replacing missing values is a common operation</font>. Pandas provides a really handy method for this problem: `fillna()`. `fillna()` provides a few different strategies for mitigating such data. For example, we can simply replace each NaN with an "Unknown":

In [ ]:
reviews.region_2.fillna("Unknown")

0                   Unknown
1                   Unknown
2         Willamette Valley
3                   Unknown
4         Willamette Valley
                ...
129966              Unknown
129967         Oregon Other
129968              Unknown
129969              Unknown
129970              Unknown
Name: region_2, Length: 129971, dtype: object

Or we could fill each missing value with the first non-null value that appears sometime after the given record in the database. This is known as the <font color='blue'> backfill strategy.

Alternatively, we may have a non-null value that we would like to replace. For example, suppose that since this dataset was published, reviewer Kerin O'Keefe has changed her Twitter handle from @kerinokeefe to @kerino. One way to reflect this in the dataset is using the replace() method:

In [ ]:
reviews.taster_twitter_handle.head()

0    @kerinokeefe
1      @vossroger
2     @paulgwine
3             NaN
4     @paulgwine
Name: taster_twitter_handle, dtype: object

In [ ]:
reviews.taster_twitter_handle.replace("@kerinokeefe", "@jason")

0              @jason
1          @vossroger
2         @paulgwine
3                 NaN
4         @paulgwine
             ...
129966            NaN
129967    @paulgwine
129968     @vossroger
129969     @vossroger
129970     @vossroger
Name: taster_twitter_handle, Length: 129971, dtype: object

Now you'll also explore how to combine data from multiple DataFrames and/or Series.

# Renaming

The first function we'll introduce here is `rename()`, which lets you change index names and/or column names. For example, to change the points column in our dataset to score, we would do:

In [ ]:
reviews.rename(columns={'points': 'score'},inplace=True)
reviews

         country  ...                                    winery
0          Italy  ...                                   Nicosia
1       Portugal  ...                       Quinta dos Avidagos
2             US  ...                                 Rainstorm
3             US  ...                                St. Julian
4             US  ...                              Sweet Cheeks
...          ...  ...                                       ...
129966   Germany  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967        US  ...                                  Citation
129968    France  ...                           Domaine Gresser
129969    France  ...                      Domaine Marcel Deiss
129970    France  ...                          Domaine Schoffit

[129971 rows x 13 columns]

- `rename()` lets you rename index or column values by specifying a index or column keyword parameter, respectively. It supports a variety of input formats, but usually a Python dictionary is the most convenient. `Here is an example using it to rename some elements of the index.`

In [ ]:
reviews.rename(index = {0: 'ZERO', 1: 'secondEntry'})

              country  ...                                    winery
ZERO            Italy  ...                                   Nicosia
secondEntry  Portugal  ...                       Quinta dos Avidagos
2                  US  ...                                 Rainstorm
3                  US  ...                                St. Julian
4                  US  ...                              Sweet Cheeks
...               ...  ...                                       ...
129966        Germany  ...  Dr. H. Thanisch (Erben Müller-Burggraef)
129967             US  ...                                  Citation
129968         France  ...                           Domaine Gresser
129969         France  ...                      Domaine Marcel Deiss
129970         France  ...                          Domaine Schoffit

[129971 rows x 13 columns]

<font color='purple'>- You'll probably rename columns very often, but rename index values very rarely. For that, **`set_index()`** is usually more convenient.</font>

# Combining

When performing operations on a dataset, we will sometimes need to combine different DataFrames

and/or Series in non-trivial ways. Pandas has three core methods for doing this. In order of increasing complexity, these are `concat()`, `join()`, and `merge()`. Most of what merge() can do can also be done more simply with `join()`, so we will omit it and focus on the first two functions here.

The simplest combining method is `concat()`. Given a list of elements, this function will smush those elements together along an axis.

This is useful when we have data in different DataFrame or Series objects but having the same fields (columns).

In [ ]:
 df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3'],
                     'C': ['C0', 'C1', 'C2', 'C3'],
                     'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3])
 df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                     'B': ['B4', 'B5', 'B6', 'B7'],
                     'C': ['C4', 'C5', 'C6', 'C7'],
                     'D': ['D4', 'D5', 'D6', 'D7']},
                    index=[4, 5, 6, 7])
 df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                     'B': ['B8', 'B9', 'B10', 'B11'],
                     'C': ['C8', 'C9', 'C10', 'C11'],
                     'D': ['D8', 'D9', 'D10', 'D11']},
                    index=[8, 9, 10, 11])
 frames = [df1, df2, df3]
 result = pd.concat(frames)
 result

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

#**`Part4`**

In [ ]:
reviews.head()

    country  ...               winery
0     Italy  ...              Nicosia
1  Portugal  ...  Quinta dos Avidagos
2        US  ...            Rainstorm
3        US  ...           St. Julian
4        US  ...         Sweet Cheeks

[5 rows x 13 columns]

# Exercises

## 1.Calculating the median of a specific column in a dataframe

What is the median of the `points` column in the `reviews` DataFrame?

In [ ]:
median_points = reviews.points.median()

median_points

88.0

## 2. Finding Unique values for any column
What countries are represented in the dataset? (Your answer should not include any duplicates.)

In [ ]:

countries = reviews['country'].unique()
countries

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt'], dtype=object)

## 3. Count uniques values for specific column
How often does each country appear in the dataset? Create a Series `reviews_per_country` mapping countries to the count of reviews of wines from that country.

In [ ]:
reviews_per_country = reviews['country'].value_counts()
reviews_per_country
#To see a list of unique values and how often they occur in a Series, use the value_counts method.

US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Serbia                       12
Czech Republic               12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Armenia                       2
Bosnia and Herzegovina        2
Egypt                         1
China                         1
Slovakia                      1
Name: country, dtype: int64

## 4. sorting according to the ratio
I'm an economical wine buyer. Which wine is the "best bargain"? Create a variable `bargain_wine` with the title of the wine with the highest points-to-price ratio in the dataset.

In [ ]:
bargain_idx = (reviews['points'] / reviews.price).idxmax()
print(bargain_idx)

64590

idxmax() function returns index of first occurrence of maximum over requested axis. While finding the index of the maximum value across any index, all NA/null values are excluded.

In [ ]:
# getting values for all the columns for that index ie 64590
bargain_wine = reviews.loc[bargain_idx]
bargain_wine

country                                                                 US
description              There's a lot going on in this Merlot, which i...
designation                                                            NaN
points                                                                  86
price                                                                    4
province                                                        California
region_1                                                        California
region_2                                                  California Other
taster_name                                                            NaN
taster_twitter_handle                                                  NaN
title                                        Bandit NV Merlot (California)
variety                                                             Merlot
winery                                                              Bandit
Name: 64590, dtype: object

In [ ]:
# now we have to get title
bargain_wine=bargain_wine['title']
print(bargain_wine)

Bandit NV Merlot (California)

## 5. Finding occurances of specific words in specific column
There are only so many words you can use when describing a bottle of wine. Is a wine more likely to be "tropical" or "fruity"? Create a Series `descriptor_counts` counting how many times each of these two words appears in the `description` column in the dataset.

In [ ]:
n_trop = reviews.description.map(lambda desc: "tropical" in desc).sum()
print(n_trop)
n_fruity = reviews.description.map(lambda desc: "fruity" in desc).sum()
print(n_fruity)
descriptor_counts = pd.Series([n_trop, n_fruity], index=['tropical', 'fruity'])

print('\n')
descriptor_counts

3607
9090

tropical    3607
fruity      9090
dtype: int64

## <font color='brown'>**`Assignments for practice`**</font> - 

https://docs.google.com/document/d/1BEDTbfMrn1RYXiYsnwDsoTJcSsJgOHpY0IKGU8BNJKU/edit?usp=sharing

https://docs.google.com/document/d/10MVTTU-eiuF6ao4FBg8ZpBRcww2TdMMHkNm90IXt8-Q/edit?usp=sharing